spring:
  aop:
    proxy-target-class: true

data:
  propertyInputFile: /properties.json
  provinceInputFile: /provinces.json

validation:
  maxBeds: 5
  minBeds: 1
  maxBaths: 5
  minBaths: 1
  maxArea: 240
  minArea: 20
